apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosetta-deployment
spec:
  selector:
    matchLabels:
      app: boinc
  replicas: 2
  template:
    metadata:
      labels:
        app: boinc
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - boinc
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: boinc
        image: boinc/client
        imagePullPolicy: Always
        env:
        - name: BOINC_GUI_RPC_PASSWORD
          value: "dfkdsksiusl"
        - name: BOINC_CMD_LINE_OPTIONS
          value: "--allow_remote_gui_rpc --attach_project https://boinc.bakerlab.org/rosetta/ 2092104_5978a9e821d31e063d77f78f0bbbdbe7"
        ports:
        - name: rpc
          containerPort: 31416
      nodeSelector:
        workload: production
