apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: http
  externalIPs:
  - 192.168.201.10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.9-alpine
        command:
        - /bin/sh
        - "-c"
        - |
          cat > /usr/share/nginx/html/index.html <<EOF
          <html>
           <head><title>Example Kubernetes Service</title></head>
           <body>
            <h1>Welcome to Example Kubernetes Service!</h1>
            <p>If you see this page, your Kubernetes cluster is up and running.</p>
           </body>
          </html>
          EOF
          exec nginx -g 'daemon off;'
        ports:
        - name: http
          containerPort: 80
