apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcg-deployment
spec:
  selector:
    matchLabels:
      app: WCG
  replicas: 3
  template:
    metadata:
      labels:
        app: WCG
    spec:
      affinity:
# Since this is a CPU intensive process we want to try and "encourage"
# the schedular to put the pods on different nodes. "preferredDuringSchedulingIgnoredDuringExecution:"
# doesn't alway work to place the pods where you think they will, but gets it right a decent amount of time.
# if we use "requiredDuringSchedulingIgnoredDuringExecution" we wind up in a deadly embrace when trying to
# do a rolling upgrade
# in this case we are matching with a name of "wcg-deployment" and whatever the hostname the pod is on
# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: metadata.name
                  operator: In
                  values:
                  - wcg-deployment
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      containers:
      - name: boinc
        image: boinc/client
        imagePullPolicy: Always
# since the official boinc/client container on docker hub always uses "latest"
# we are stuck with "imagePullPolicy: Always" if we want an update container
        resources:
#without some resource limits, boinc will consume the entire cluster
          limits:
            memory: "2200Mi"
            cpu: "500m"
          requests:
            cpu: 500m
            memory: 1000Mi
        env:
        - name: BOINC_GUI_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wcg-secrets
              key: boinc_gui_rpc_password.txt
        - name: BOINC_WEAK_KEY
          valueFrom:
            secretKeyRef:
              name: wcg-secrets
              key: wcg_weak_key.txt
        - name: BOINC_CMD_LINE_OPTIONS
          value: "--allow_remote_gui_rpc --attach_project http://www.worldcommunitygrid.org/ $(BOINC_WEAK_KEY)"
        ports:
        - name: rpc
#32416 is the standard port for the boinc gui
          containerPort: 31416
      nodeSelector:
# since the kurnetes cluster master in our case is a much smaller VM than the two compute nodes,
# we put the production label on the compute nodes to keep the production workload off the master.
        workload: production
