apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcg-deployment
spec:
  selector:
    matchLabels:
      app: boinc
  replicas: 2
  template:
    metadata:
      labels:
        app: boinc
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: metadata.name
                operator: In
                values:
                - wcg-deployment
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: boinc
        image: boinc/client
        imagePullPolicy: Always
        env:
        - name: BOINC_GUI_RPC_PASSWORD
          value: "dfkdsksiusl"
        - name: BOINC_CMD_LINE_OPTIONS
          value: "--allow_remote_gui_rpc --attach_project https://www.worldcommunitygrid.org/ 1116355_f79e41e00ba5f77c01db0b634fc4c7cd"
        ports:
        - name: rpc
          containerPort: 31416
      nodeSelector:
        workload: production
